GET https://secret-lowlands-10364.herokuapp.com/plants

###

GET https://secret-lowlands-10364.herokuapp.com/orders

###

GET https://secret-lowlands-10364.herokuapp.com/orders/7

###

POST https://secret-lowlands-10364.herokuapp.com/orders
Content-Type: application/json

{
  "username": "test username",
  "address": "test address",
  "qty": 12,
  "plantId": 0 
}
###

POST https://secret-lowlands-10364.herokuapp.com/reset

###

GET http://localhost:3000/plants

###

GET http://localhost:3000/orders

###

GET http://localhost:3000/orders/2

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "username": "test username",
  "address": "test address",
  "qty": 12,
  "plantId": 0 
}

