//Production=======================
GET https://herald-plants-api.herokuapp.com/plants

###

GET https://herald-plants-api.herokuapp.com/orders

###

GET https://herald-plants-api.herokuapp.com/orders/7

###

POST https://herald-plants-api.herokuapp.com/orders
Content-Type: application/json

{
  "username": "test username",
  "address": "test address",
  "qty": 12,
  "plantId": 1
}
###

DELETE https://herald-plants-api.herokuapp.com/reset

###
//Development======================
GET http://localhost:3000/

###

GET http://localhost:3000/orders

###

GET http://localhost:3000/orders/2

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "username": "test username",
  "address": "test address",
  "qty": 12,
  "plantId": 1
}

###

DELETE http://localhost:3000/reset

